version: "3"

services:
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: "polyaxon"
      POSTGRES_PASSWORD: "polyaxon"
    networks:
      - api

  memcache:
    image: memcached
    networks:
      - api

  redis:
    image: redis:3.0-alpine
    networks:
      - api

  web:
    build: ./
    command: python3 polyaxon/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - api
    depends_on:
      - memcache
      - postgres
      - redis
    volumes:
      - .:/polyaxon
    ports:
      - "8000:8000"
      - "6006:6006"
      - "8888:8888"

    environment:
      DJANGO_SETTINGS_MODULE: api.settings
      MEMCACHE_LOCATION: "memcache:11211"
      SETTINGS_ENV_DIR: "dev"
      DATABASE_URL: "postgres://polyaxon:polyaxon@postgres:5432/polyaxon"
      REDIS_CELERY_BROKER_URL: "redis://redis:6379/0"
      REDIS_CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      REDIS_CELERY_JOB_STATUS_URL: "redis://redis:6379/2"

  worker:
    build:
      context: ./
    volumes:
      - .:/polyaxon
    environment:
      REDIS_CELERY_BROKER_URL: "redis://redis:6379/0"
      REDIS_CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      REDIS_CELERY_JOB_STATUS_URL: "redis://redis:6379/2"
    networks:
      - api
    depends_on:
      - redis


networks:
  api:
